id: P40241BB1
initial_creation_type: ocr
source_metadata:
  volumes:
    3eb9a57d4d4d4008ae3b465e371af878:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
